Предсказание рака лёгких

● Проведите разведочный анализ данных
● Воспользуйтесь логистической регрессией
из пакета sklearn
● Оформите результат в виде ноутбука Jupiter

Описание данных
GENDER: M [Male], F [Female]
AGE: Age of patients
SMOKING: 2 [Yes], 1 [No]
YELLOW_FINGERS: 2 [Yes], 1 [No]
ANXIETY: 2 [Yes], 1 [No]
PEER_PRESSURE: 2 [Yes], 1 [No]
CHRONIC DISEASE: 2 [Yes], 1 [No]
FATIGUE: 2 [Yes], 1 [No]
ALLERGY: 2 [Yes], 1 [No]
WHEEZING: 2 [Yes], 1 [No]
ALCOHOL CONSUMING: 2 [Yes], 1 [No]
COUGHING: 2 [Yes], 1 [No]
SHORTNESS OF BREATH: 2 [Yes], 1 [No]
SWALLOWING DIFFICULTY: 2 [Yes], 1 [No]
CHEST PAIN: 2 [Yes], 1 [No]
LUNG_CANCER: YES [Positive], NO [Negative]

Посмотрим на датасет

In [98]:
import pandas as pd


data = pd.read_csv('./csvs/survey lung cancer.csv')
data.head()

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,LUNG_CANCER
0,M,69,1,2,2,1,1,2,1,2,2,2,2,2,2,YES
1,M,74,2,1,1,1,2,2,2,1,1,1,2,2,2,YES
2,F,59,1,1,1,2,1,2,1,2,1,2,2,1,2,NO
3,M,63,2,2,2,1,1,1,1,1,2,1,1,2,2,NO
4,F,63,1,2,1,1,1,1,1,2,1,2,2,1,1,NO

In [99]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 309 entries, 0 to 308
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   GENDER                 309 non-null    object
 1   AGE                    309 non-null    int64
 2   SMOKING                309 non-null    int64
 3   YELLOW_FINGERS         309 non-null    int64
 4   ANXIETY                309 non-null    int64
 5   PEER_PRESSURE          309 non-null    int64
 6   CHRONIC DISEASE        309 non-null    int64
 7   FATIGUE                309 non-null    int64
 8   ALLERGY                309 non-null    int64
 9   WHEEZING               309 non-null    int64
 10  ALCOHOL CONSUMING      309 non-null    int64
 11  COUGHING               309 non-null    int64
 12  SHORTNESS OF BREATH    309 non-null    int64
 13  SWALLOWING DIFFICULTY  309 non-null    int64
 14  CHEST PAIN             309 non-null    int64
 15  LUNG_CANCER            309 non-null    object
dtypes: int64(14), object(2)
memory usage: 38.8+ KB

In [100]:
data.describe()

,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN
count,309.000000,309.000000,309.000000,309.000000,309.000000,309.000000,309.000000,309.000000,309.000000,309.000000,309.000000,309.000000,309.000000,309.000000
mean,62.673139,1.563107,1.569579,1.498382,1.501618,1.504854,1.673139,1.556634,1.556634,1.556634,1.579288,1.640777,1.469256,1.556634
std,8.210301,0.496806,0.495938,0.500808,0.500808,0.500787,0.469827,0.497588,0.497588,0.497588,0.494474,0.480551,0.499863,0.497588
min,21.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,57.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
50%,62.000000,2.000000,2.000000,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,1.000000,2.000000
75%,69.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000
max,87.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000

In [101]:
data.isna().sum()

GENDER                   0
AGE                      0
SMOKING                  0
YELLOW_FINGERS           0
ANXIETY                  0
PEER_PRESSURE            0
CHRONIC DISEASE          0
FATIGUE                  0
ALLERGY                  0
WHEEZING                 0
ALCOHOL CONSUMING        0
COUGHING                 0
SHORTNESS OF BREATH      0
SWALLOWING DIFFICULTY    0
CHEST PAIN               0
LUNG_CANCER              0
dtype: int64

In [102]:
data.rename(columns={'CHRONIC DISEASE':'CHRONIC_DISEASE', 'ALCOHOL CONSUMING':'ALCOHOL_CONSUMING', 'SHORTNESS OF BREATH':'SHORTNESS_OF_BREATH',
                   'SWALLOWING DIFFICULTY':'SWALLOWING_DIFFICULTY', 'CHEST PAIN':'CHEST_PAIN'}, inplace=True)

In [103]:
data.sample(7)

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC_DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL_CONSUMING,COUGHING,SHORTNESS_OF_BREATH,SWALLOWING_DIFFICULTY,CHEST_PAIN,LUNG_CANCER
158,F,56,1,1,2,2,2,2,2,2,2,1,2,2,2,YES
242,M,77,2,2,2,1,2,1,2,2,1,1,1,2,2,YES
97,M,59,2,1,1,2,1,1,1,1,2,2,2,1,1,YES
249,M,68,2,1,2,1,1,2,1,1,1,1,1,1,1,NO
300,F,63,2,2,2,2,2,2,2,2,1,2,2,2,2,YES
280,F,59,2,1,1,1,2,2,2,1,1,1,2,1,1,NO
83,F,81,1,1,1,2,2,1,2,1,2,2,2,1,1,YES

Подготовка данных

In [104]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

data.GENDER = data.GENDER.replace({'M': 'Male', 'F': 'Female'})
data.LUNG_CANCER = label_encoder.fit_transform(data.LUNG_CANCER)  # YES == 1, NO == 0
data.GENDER = label_encoder.fit_transform(data.GENDER) # Male == 1, Female == 0

In [105]:
data.sample(7)

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC_DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL_CONSUMING,COUGHING,SHORTNESS_OF_BREATH,SWALLOWING_DIFFICULTY,CHEST_PAIN,LUNG_CANCER
56,0,63,1,2,1,2,1,2,1,1,1,2,2,1,2,1
34,1,59,1,2,2,1,1,1,1,1,1,1,1,2,2,0
38,1,56,2,1,1,1,2,1,1,2,1,1,2,1,2,1
230,1,78,1,2,1,2,2,2,1,2,1,1,2,2,2,1
128,0,58,2,2,2,2,1,2,1,1,1,2,2,2,1,1
228,0,56,1,2,1,2,1,2,1,1,1,2,2,1,2,1
218,0,70,1,1,1,2,2,1,2,1,2,2,2,1,1,1

In [106]:
data.dtypes

GENDER                   int64
AGE                      int64
SMOKING                  int64
YELLOW_FINGERS           int64
ANXIETY                  int64
PEER_PRESSURE            int64
CHRONIC_DISEASE          int64
FATIGUE                  int64
ALLERGY                  int64
WHEEZING                 int64
ALCOHOL_CONSUMING        int64
COUGHING                 int64
SHORTNESS_OF_BREATH      int64
SWALLOWING_DIFFICULTY    int64
CHEST_PAIN               int64
LUNG_CANCER              int64
dtype: object

In [107]:
y = data.LUNG_CANCER
x = data.drop('LUNG_CANCER', axis=1)


from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y)

In [108]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(x_train)
x_train_scaled = pd.DataFrame(x_train_scaled, columns=x.columns)

x_test_scaled = scaler.fit_transform(x_test)
x_test_scaled = pd.DataFrame(x_test_scaled, columns=x.columns)

In [109]:
x_train_scaled.head()

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC_DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL_CONSUMING,COUGHING,SHORTNESS_OF_BREATH,SWALLOWING_DIFFICULTY,CHEST_PAIN
0,-1.021884,1.786406,-1.196486,-1.164965,-1.057954,1.004338,0.987096,0.734847,0.889212,0.928926,0.937043,-1.134517,-1.310590,-0.970143,0.850812
1,-1.021884,1.786406,0.835781,0.858395,0.945221,1.004338,0.987096,0.734847,-1.124591,-1.076512,-1.067187,-1.134517,0.763015,1.030776,-1.175348
2,0.978584,0.930011,0.835781,-1.164965,-1.057954,-0.995680,-1.013072,0.734847,0.889212,0.928926,0.937043,0.881432,0.763015,-0.970143,0.850812
3,-1.021884,-0.293409,-1.196486,0.858395,0.945221,-0.995680,-1.013072,-1.360828,-1.124591,-1.076512,-1.067187,0.881432,-1.310590,-0.970143,-1.175348
4,-1.021884,1.419380,-1.196486,0.858395,0.945221,1.004338,0.987096,0.734847,-1.124591,0.928926,0.937043,-1.134517,-1.310590,-0.970143,-1.175348

In [110]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report


lr = LogisticRegression(solver="liblinear")

lr.fit(x_train_scaled, y_train)
y_pred = lr.predict(x_test_scaled)
lr_report = classification_report(y_test, y_pred)
lr_acc = round(accuracy_score(y_test, y_pred)*100, 2)

print(f'\nClassification report:\n\n {lr_report}')
print(f'\nAccuary score {lr_acc}%')

Classification report:

               precision    recall  f1-score   support

           0       0.71      0.71      0.71         7
           1       0.97      0.97      0.97        71

    accuracy                           0.95        78
   macro avg       0.84      0.84      0.84        78
weighted avg       0.95      0.95      0.95        78


Accuary score 94.87%

С вероятностью 87-95% выявляет рак на наших данных